# ADM Homework 1

# Problem1

## Introduction

### Say "Hello, World!" With Python

In [1]:
print("Hello, World!")

Hello, World!


### Arithmetic Operators

In [3]:
a = int(input())
b = int(input())
print(a+b)
print(a-b)
print(a*b)

3
2
5
1
6


### Python: Division

In [4]:
a = int(input())
b = int(input())
print(a//b)
print(a/b)

4
3
1
1.3333333333333333


### Loops

In [5]:
n = int(input())
for i in range(n):
    print(i*i)

5
0
1
4
9
16


### Write a function

In [6]:
def is_leap(year):
    leap = False
    # Write your logic here
    if(year%400==0 or (year%100!=0 and year%4==0)):
        leap = True
    return leap

year = int(input())
print(is_leap(year))

1990
False


### Print Function

In [8]:
from __future__ import print_function
if __name__ == '__main__':
    n = int(input())
    if(n<10):
        t=10**(n-1)
        s=0
        for i in range(1,n+1):
            s=s+i*t
            t=t/10
        print(s)
    else:
        for i in range(1,n+1):
            print(i,end='')

3
123.0


### Python If-Else

In [13]:
#!/bin/python
import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input().strip())
if(n%2!=0):
    print("Weird")
elif(n%2==0 and n>=2 and n<=5):
    print("Not Weird")
elif(n%2==0 and n>=6 and n<=20):
    print("Weird")
else:
    print("Not Weird")


3
Weird


## Basic Datatypes

### Find the Runner-Up Score!

In [28]:
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int,input().split()))
    max1=-101
    for i in range(n):
        if(max1<arr[i]):
            max1=arr[i]
    max2=-101        
    for i in range(n):
        if(arr[i]== max1):
            arr[i]=-200
    for i in range(n):
        if(max2<arr[i]):
            max2=arr[i]
    print(max2)

5
2 3 6 6 5
5


### List Comprehensions

In [30]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    l=[]
    l=[[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1) if(i+j+k)!=n]
    print(l)


1
1
1
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


### Nested Lists

In [31]:
if __name__ == '__main__':
    l=[]
    for _ in range(int(input())):
        name = input()
        score = float(input())
        l.append([name,score])
    m = sorted(set([i[1] for i in l]))[1]
    print("\n".join(sorted([i[0] for i in l if i[1] == m])))

4
Prashant
32
Pallavi
36
Dheeraj
39
Shivam
40
Pallavi


### Finding the percentage

In [34]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        line = input().split()
        name, scores = line[0], line[1:]
        scores = list(map(float, scores))
        student_marks[name] = scores
    query_name = input()
    s = sum(student_marks[query_name])/len(student_marks[query_name])
    format_s = "{:.2f}".format(s)
    print(format_s)
    student_marks[query_name]=sum(scores)

3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
56.00


### List

In [35]:
def insert(ind, val):
    l.insert(ind, val)  
def append(val):
    l.append(val)
def pop():
    l.pop() 
def remove(val):
    l.remove(val)
def sort():
    l.sort()
def reverse():
    l.reverse()
    
n = int(input())
l = []
arr = [input() for i in range(n)]

for i in arr:
    s = i.split()
    if s[0] == 'insert':
        insert(ind=int(s[1]), val=int(s[2]))
    elif s[0] == 'append':
        append(val=int(s[1]))
    elif s[0] == 'pop':
        pop()
    elif s[0] == 'print':
        print(l)
    elif s[0] == 'remove':
        remove(val=int(s[1]))
    elif s[0] == 'sort':
        sort()
    elif s[0] == 'reverse':
        reverse()
    


12
insert 0 5
insert 1 10 
insert 0 6 
print
remove 6 
append 9 
append 1 
sort 
print 
pop 9
reverse 
print
[6, 5, 10]
[1, 5, 9, 10]
[9, 5, 1]


### Tuples

In [36]:
if __name__ == '__main__':
    n = int(input())
    integer_list = list(map(int,input().split()))
    print(hash(tuple(integer_list)))


2
1 2
-3550055125485641917


## Strings

### sWAP cASE

In [14]:
def swap_case(s):
    l=[]
    sn=''
    for i in range(len(s)):
        if(s[i].isupper()):
            l.append(s[i].lower())
        else:
            l.append(s[i].upper())
    for i in range(len(l)):
        sn=sn+l[i]
    return sn
if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

HackerRank.com presents "Pythonist 2".
hACKERrANK.COM PRESENTS "pYTHONIST 2".


### String Split and Join

In [15]:
def split_and_join(line):
    l=line.split()
    l="-".join(l)
    return l
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

this is a string
this-is-a-string


### What's Your Name?

In [16]:
def print_full_name(first, last):
    print('Hello '+ first + ' ' + last + '! You just delved into python.')
if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Ross
Taylor
Hello Ross Taylor! You just delved into python.


### Mutations

In [17]:
def mutate_string(string, position, character):
    l=[]
    s_new=""
    for i in range(len(string)):
        if(i == position):
            l.append(character)
        else:
            l.append(string[i])
    for i in range(len(l)):
        s_new=s_new+l[i]
    string = s_new
    return string
if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

abracadabra
5 k
abrackdabra


### Find a string

In [18]:
def count_substring(string, sub_string):
    l=[]
    for i in range(len(string)-len(sub_string)+1):
        s=string[i:i+len(sub_string)]
        l.append(s)
        s=""
    count=0
    for i in range(len(l)):
        if(l[i]==sub_string):
            count=count+1;
    return count
if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

ABCDCDC
CDC
2


### String Validators

In [20]:
if __name__ == '__main__':
    s = input()
    t1=t2=t3=t4=t5=False
    for i in range(len(s)):
        if(s[i].isalnum()):
            t1=True
        if(s[i].isalpha()):
            t2=True
        if(s[i].isdigit()):
            t3=True
        if(s[i].islower()):
            t4=True
        if(s[i].isupper()):
            t5=True
    print(t1)
    print(t2)
    print(t3)
    print(t4)
    print(t5)

qA2
True
True
True
True
True


### Capitalize!

In [23]:
def solve(s):
    sn=""
    sn=s[0].upper()
    for i in range(len(s)-1): 
        if(s[i]==" "):
            sn=sn + s[i+1].upper()
        else:
            sn=sn+s[i+1]
    print(sn)

s = input()
result = solve(s)



hello world
Hello World


### TextWrap

In [37]:
import textwrap
def wrap(string, max_width):
    return '\n'.join([(string[i:i+max_width]) for i in range(0,len(string),max_width)])
#first I used list comprehension to be compress my loop and got list: ['ABCD', 'EFGH', 'IJKL', 'IMNO', 'QRST','UVWX', 'YZ']
#after that I needed to change the list to string with ''.join function
#modify '' like '\n',cuz i need new line

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

ABCDEFGHIJKLIMNOQRSTUVWXYZ
4
ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ


### Text Alignment

In [38]:
l1 = 5
s = 'H'
for i in range(l1):
    print((s*i+s).rjust(5,' ')+(s*i))
l2 = 6
for i in range(l2):
    print((5*s).rjust(7,' ')+(5*s).rjust(20,' '))
l3 = 3
for i in range(l3):
    print((25*s).rjust(27,' '))
l4 = 6
for i in range(l4):
    print((5*s).rjust(7,' ')+(5*s).rjust(20,' '))
l5 = 5
for i in range(l5-1,0,-1):
    print((s*i+s).rjust(25,' ')+(s*i))
print(s.rjust(25,' '))


    H
   HHH
  HHHHH
 HHHHHHH
HHHHHHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
  HHHHHHHHHHHHHHHHHHHHHHHHH
  HHHHHHHHHHHHHHHHHHHHHHHHH
  HHHHHHHHHHHHHHHHHHHHHHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
  HHHHH               HHHHH
                    HHHHHHHHH
                     HHHHHHH
                      HHHHH
                       HHH
                        H


### String Formatting

In [39]:
def print_formatted(x):
    for i in range(1,x+1):
        print(i,oct(i)[2:],hex(i)[2:].capitalize(),bin(i)[2:],sep = " ")
if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

17
1 1 1 1
2 2 2 10
3 3 3 11
4 4 4 100
5 5 5 101
6 6 6 110
7 7 7 111
8 10 8 1000
9 11 9 1001
10 12 A 1010
11 13 B 1011
12 14 C 1100
13 15 D 1101
14 16 E 1110
15 17 F 1111
16 20 10 10000
17 21 11 10001


### Merge the Tools!

In [40]:
def merge_the_tools(s,k):
    sub=[(s[i:i+k]) for i in range(0,len(s),k)]
    ss=[]
    for i in range(len(sub)):
        ss.append("".join(set(sub[i])))
    for i in range(len(sub)):
        print(ss[i][::-1])
        
if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

AABCAAADA
3
BA
AC
AD


## Sets

### Introduction to Sets

In [41]:
def average(array):
    array=set(array)
    return sum(array)/len(array)
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


### No Idea!

In [42]:
N,M = list(map(int,input().split()))
arr=map(int,input().split())
a =  set(map(int,input().split()))
b = set(map(int,input().split()))
c=0
for i in arr:
    if(i in a):
        c=c+1
    elif(i in b):
        c=c-1
print(c)

3 2
1 5 3
3 1
5 7
1


### Symmetric Difference

In [43]:
M = int(input())
a = set(map(int,input().split()))
N = int(input())
b = set(map(int,input().split()))
s1=a.difference(b)
s2=b.difference(a)
s=sorted(s1.union(s2))
for i in s:
    print(i, end="\n")


4
2 4 5 9
4
2 4 11 12
5
9
11
12


### Set .add()

In [45]:
n = int(input())
count = set()
for i in range(n):
    count.add(input())
print(len(count))


7
UK
China
USA
France
New Zealand
UK
France
5


### Set .discard(), .remove() & .pop()

In [47]:
n = int(input())
s = set(map(int, input().split()))
N = int(input())
for i in range(N):
    l = input().split()
    if l[0]=="remove" :
        s.remove(int(l[1]))
    elif l[0]=="discard" :
        s.discard(int(l[1]))
    elif l[0]=="pop" :
        s.pop()
print(sum(s))


9
1 2 3 4 5 6 7 8 9
10
pop
remove 9
discard 9
discard 8
remove 7
pop
discard 6
remove 5
pop
discard 5
4


### Set .union() 

In [48]:
M = int(input())
a = set(map(int,input().split()))
N = int(input())
b = set(map(int,input().split()))
print(len(a.union(b)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


### Set .intersection()

In [49]:
M = int(input())
a = set(map(int,input().split()))
N = int(input())
b = set(map(int,input().split()))
print(len(a.intersection(b)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


### Set .difference()

In [50]:
M = int(input())
a = set(map(int,input().split()))
N = int(input())
b = set(map(int,input().split()))
print(len(a.difference(b)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


### Set .symmetric_difference() 

In [51]:
M = int(input())
a = set(map(int,input().split()))
N = int(input())
b = set(map(int,input().split()))
print(len(a.symmetric_difference(b)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


### Set Mutations

In [52]:
M = int(input())
a = set(map(int,input().split()))
N = int(input())
for i in range(N):
    l,i = input().split()
    b = set(map(int, input().split()))
    if(l == "update"):
        a.update(b)
    elif(l == "intersection_update"):
        a.intersection_update(b)
    elif(l == "symmetric_difference_update"):
        a.symmetric_difference_update(b)
    elif(l == "difference_update"):
        a.difference_update(b)
print(sum(a))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


### The Captain's Room

In [53]:
K = int(input())
s = input().split()
s.sort()
p = (set(s[0::2]) ^ set(s[1::2]))
capt=p.pop()
print(capt)

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


### Check Subset

In [54]:
T= int(input())
for i in range(T):
    n1 = int(input())
    A=set(input().split())
    n2 = int(input())
    B=set(input().split())
    print(A.intersection(B) == A)

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


### Check Strict Superset

In [55]:
A=set(input().split())
N=int(input())
for i in range(N):
    s=set(map(int,(input().split())))
    if A.issuperset(s):
        print(True)
    else:
        print(False)
        break


1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
False


## Collections

### collections.Counter()

In [56]:
from collections import Counter

X = int(input())
l= Counter(map(int,input().split()))
N = int(input())
s=0
for i in range(N):
    size,price = map(int, input().split())
    if l[size]:
        s=s+price
        l[size]=l[size]-1
print(s)


10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50
200


### DefaultDict Tutorial

In [58]:
from collections import defaultdict
d = defaultdict(list)
n , m = map(int,input().split())
a,b = [input() for i in range(n)],[input() for i in range(m)]
for i in range(len(a)):
    d[a[i]].append(str(i+1))
for i in b:
    if i in a:
        print(' '.join(d[i]))
    else:
        print(-1)


5 2
a
a
b
a
b
a
b
1 2 4
3 5


### Collections.namedtuple()

In [59]:
N = int(input())
m = input().split().index("MARKS")
d = [input().split() for i in range(N)]
print(sum(int(i[m]) for i in d)/N)


5
ID         MARKS      NAME       CLASS 
1          97         Raymond    7 
2          50         Steven     4     
3          91         Adrian     9  
4          72         Stewart    5  
5          80         Peter      6 
78.0


### Collections.deque()


In [60]:
from collections import deque
d = deque()
N=int(input())
for i in range(N):
    a = input().split()
    if a[0]=="append":
        d.append(a[1])
    elif a[0]=="appendleft":
        d.appendleft(a[1])
    elif a[0]=="pop":
        d.pop()
    elif a[0]=="popleft":
        d.popleft()
print(*d)


6
append 1
append 2
append 3
appendleft 4
pop
popleft
1 2


### Company Logo

In [61]:
#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter



if __name__ == '__main__':
    s = input()
    x=Counter(s)
    for i in x.most_common(3):
        print(*i) 


aabbbccde
b 3
a 2
c 2


## Date and Time 

### Calendar Module 

In [62]:
import calendar
l=list(map(int,input().split()))
month = l[0]
day = l[1]
year = l[2]
d={0:'Monday' , 1:'Tuesday',  2:'Wednesday', 3:'Thursday', 4:'Friday', 5:'Saturday', 6:'Sunday'}
print(d[calendar.weekday(year,month,day)].upper())


08 05 2015
WEDNESDAY


### Time Delta 

In [67]:
#!/bin/python3

import math
import os
import random
import re
import sys
from datetime import datetime

# Complete the time_delta function below.
def time_delta(t1, t2):
    dt1=datetime.strptime(t1,'%a %d %b %Y %H:%M:%S %z')
    dt2=datetime.strptime(t2,'%a %d %b %Y %H:%M:%S %z')
    print(str(int(abs(dt1-dt2).total_seconds())))

t = int(input())
for t_itr in range(t):
    t1 = input()
    t2 = input()
    delta = time_delta(t1, t2)

2
Sun 10 May 2015 13:54:36 -0700
Sun 10 May 2015 13:54:36 -0000
25200
Sat 02 May 2015 19:54:36 +0530
Fri 01 May 2015 13:54:36 -0000
88200


## Errors and Exceptions 

### Exceptions 

In [68]:
T=int(input())
for i in range(T):
    try:
        a,b=map(int,input().split())
        print(a//b)
    except Exception as e:
        print("Error Code:",e)

3
1 0
Error Code: integer division or modulo by zero
2 $
Error Code: invalid literal for int() with base 10: '$'
3 1
3


### Built-Ins

### Zipped!

In [69]:
N,X = map(int, input().split()) 
d=[map(float, input().split()) for _ in range(X)] 
for i in zip(*d): 
    print( sum(i)/len(i) )


5 3
89 90 78 93 80
90 91 85 88 86  
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


### Input()

In [70]:
x,k=map(int, input().split())
print (k==eval(input()))

1 4
x**3 + x**2 + x + 1
True


### Python Evaluation

In [71]:
eval(input())

print(2 + 3)
5


### Athlete Sort

In [72]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nm = input().split()
    n = int(nm[0])
    m = int(nm[1])
    arr = []
    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))
    k = int(input())
    arr.sort(key=lambda i: i[k])
    for i in range(n):
        print(*arr[i])
        


5 3
10 2 5
7 1 0
9 9 9
1 23 12
6 5 9
1
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


###  Any or All


In [73]:
N=int(input()) 
a=input().split(' ') 
print(all(int(i)>=0 for i in a) and any(i == i[::-1]for i in a))


5
12 9 61 5 14
True


### ginortS

In [74]:
s = input()
low=[]
up=[]
num=[]
odd=[]
ev=[]
ss=''
for i in range(len(s)):
    if(s[i].isdigit()):
        num.append(s[i])
    elif(s[i].isupper()):
        up.append(s[i])
    elif(s[i].islower()):
        low.append(s[i])
low=sorted(low)
up=sorted(up)
#print(num)
for i in range(len(num)):
    if(int(num[i])%2!=0):
        odd.append(num[i])
    else:
        ev.append(num[i])
odd=sorted(odd)
ev=sorted(ev)
num=odd+ev
#print(num)
ss=low+up+num
for i in ss:
    print(i, end="")


Sorting1234
ginortS1324

## Python Functionals 

### Map and Lambda Function 

In [75]:
cube = lambda x: x*x*x 

def fibonacci(n):
    l = [0,1]
    for i in range(2,n):
        l.append(l[i-2] + l[i-1])
    return(l[0:n])
        

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


## Regex and Parsing

### Detect Floating Point Number 

In [76]:
for _ in range(int(input())):
    try:
        print(bool(float(input())))
    except:
        print('False')


3
+4.54
True
4
True
SomeRandomStuff
False


### Re.split() 

In [77]:
regex_pattern = r"[,.]"	# Do not delete 'r'.

import re
print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


### Group(), Groups() & Groupdict() 

In [78]:
import re
text=input()
x = re.search(r"([a-zA-Z0-9])\1",text )
print(x.group(1) if x else -1)


12345678910111213141516171820212223
1


### Validating Roman Numerals 

In [79]:
regex_pattern = r"(?<=^)M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})(?=$)"	# Do not delete 'r'.

import re
print(str(bool(re.match(regex_pattern, input()))))

CDXXI
True


### Validating phone numbers 

In [80]:
import re
N=int(input())
for i in range(N):
    s=input()
    if re.match("^[789][0-9]{9}$",s):
        print("YES")
    else:
        print("NO")


2
9587456281
YES
1252478965
NO


## XML

### XML 1 - Find the Score

In [ ]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    s=0
    for i in node.iter():
        s=s+len(i.items())
    return s

if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))
##Compilation success in hackerrank

### XML2 - Find the Maximum Depth

In [84]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    for i in elem:
        depth(i, level+1)
    maxdepth = max(level+1, maxdepth)

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
  <title>HackerRank</title>
  <subtitle lang='en'>Programming challenges</subtitle>
  <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
  <updated>2013-12-25T12:00:00</updated>
</feed>
1


## Numpy 

### Arrays

In [27]:
import numpy as np
def arrays(arr):
    b = np.array(arr,float)
    return b[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### Shape and Reshape

In [85]:
import numpy as np
print(np.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose and Flatten

In [86]:
import numpy as np
N,M = map(int,(input().split()))
a = np.array([input().split() for i in range(N)],int)
print(a.transpose())
print(a.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### Concatenate

In [87]:
import numpy as np
N,M,P = map(int,(input().split()))
a = np.array([input().split() for i in range(N)],int)
b = np.array([input().split() for i in range(M)],int)
print(np.concatenate((a, b)))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Zeros and Ones

In [88]:
import numpy as np
n = list(map(int,(input().split())))
print(np.zeros((n),int)) 
print(np.ones((n),int))


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### Eye and Identity

In [89]:
import numpy as np
N,M = map(int,(input().split()))
np.set_printoptions(legacy='1.13')
print(np.eye(N,M))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Array Mathematics

In [90]:
import numpy as np
N,M = map(int,(input().split()))


a = np.array([(list(map(int, input().split()))) for i in range(N)],int)
b = np.array([(list(map(int, input().split()))) for i in range(N)],int)
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.floor_divide(a, b))
print(np.mod(a, b))
print(np.power(a, b))
  

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### Floor, Ceil and Rint

In [91]:
import numpy as np
a=(np.array(input().split(),float))
np.set_printoptions(legacy='1.13')
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### Sum and Prod

In [92]:
import numpy as np
N,M = map(int,(input().split()))
a = np.array([(list(map(int, input().split()))) for i in range(N)],int)
print(np.prod(np.sum(a,axis=0),axis=0))

2 2
1 2
3 4
24


### Min and Max

In [93]:
import numpy as np
N,M = map(int,(input().split()))
a = np.array([(list(map(int, input().split()))) for i in range(N)],int)
print(max(np.min(a,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


### Mean, Var, and Std

In [94]:
import numpy as np
N,M = map(int,(input().split()))
a = np.array([(list(map(int, input().split()))) for i in range(N)],int)
print(np.mean(a,axis=1))
print(np.var(a,axis=0))
print(round(np.std(a),11))

2 2
1 2 
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### Dot and Cross

In [95]:
import numpy as np
N = int(input())
a = np.array([(list(map(int, input().split()))) for i in range(N)],int)
b = np.array([(list(map(int, input().split()))) for i in range(N)],int)
print(np.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### Inner and Outer

In [96]:
import numpy as np
a = np.array(input().split(),int)
b = np.array(input().split(),int)
print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


### Polynomials

In [97]:
import numpy as np
P = np.array(input().split(),float)
x = int(input())
print(np.polyval(P,x))

1.1 2 3
0
3.0


### Linear Algebra

In [98]:
import numpy as np
N = int(input())
a = np.array([(list(map(float, input().split()))) for i in range(N)],float)
print(round(np.linalg.det(a),2))

2
1.1 1.1
1.1 1.1
0.0


# Problem2

## Birthday Cake Candles

In [103]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'birthdayCakeCandles' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY candles as parameter.
#

def birthdayCakeCandles(candles):
    max_c=-1000
    s=0
    for i in range(len(candles)):
        if(candles[i]>max_c):
            max_c=candles[i]
    for i in range(len(candles)):
        if(candles[i]==max_c):
            s+=1
    print(s)


candles_count = int(input().strip())
candles = list(map(int, input().rstrip().split()))
result = birthdayCakeCandles(candles)


4
3 2 1 3
2


## Number Line Jumps

In [104]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'kangaroo' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER x1
#  2. INTEGER v1
#  3. INTEGER x2
#  4. INTEGER v2
#

def kangaroo(x1, v1, x2, v2):
    s1=x1
    s2=x2
    for i in range(10001):
        s1=s1+v1
        s2=s2+v2
        if(s1==s2):
            print('YES')
    else:
        print('NO')


first_multiple_input = input().rstrip().split()
x1 = int(first_multiple_input[0])
v1 = int(first_multiple_input[1])
x2 = int(first_multiple_input[2])
v2 = int(first_multiple_input[3])
result = kangaroo(x1, v1, x2, v2)

0 3 4 2
YES
NO


## Viral Advertising

In [106]:
#!/bin/python3
import math
import os
import random
import re
import sys
#
# Complete the 'viralAdvertising' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def viralAdvertising(n):
    shared=5
    liked=math.floor(shared/2)
    c=liked
    for i in range (1,n):
        shared=liked*3
        liked=math.floor(shared/2)
        c=c+liked
    return(c)


n = int(input().strip())
result = viralAdvertising(n)
print(result)

3
9


## Recursive Digit Sum

In [107]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n,k):
    if (int(n)<10): 
        return int(n)
    l = list(map(int, str(n)))
    return superDigit(str(sum(l)*k),1)  

first_multiple_input = input().rstrip().split()
n = first_multiple_input[0]
k = int(first_multiple_input[1])
result = superDigit(n, k)
print(result)


148 3
3


## Insertion Sort - Part 1

In [108]:
#!/bin/python3
##Use pseudocode from wikipedia
import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    i=1
    while(i < len(arr)):
        key = arr[i]
        j = i-1
        while(j >= 0 and key < arr[j]):
            arr[j + 1] = arr[j]
            j =j - 1
            print(*arr)
        arr[j + 1] = key
        i=i+1
    print(*arr)

n = int(input().strip())
arr = list(map(int, input().rstrip().split()))
insertionSort1(n, arr)


5
2 4 6 8 3
2 4 6 8 8
2 4 6 6 8
2 4 4 6 8
2 3 4 6 8


## Insertion Sort - Part 2

In [109]:
#!/bin/python3
## Just delete print from insertion_sort1
import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort2' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort2(n, arr):
    i=1
    while(i < len(arr)):
        key = arr[i]
        j = i-1
        while(j >= 0 and key < arr[j]):
            arr[j + 1] = arr[j]
            j =j - 1
        arr[j + 1] = key
        i=i+1
        print(*arr)

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)


6
1 4 3 5 6 2
1 4 3 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 2 3 4 5 6
